### ISSUE TITLE
Jenkins job should probably depend on latest ODK

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/pipeline-mp#2]
Right now, the ODK version is hard coded to 1.2.7; better to just download odk:latest; these are tested intensively and should not break anything.

**Comment by kltm** [comment]
As a note, locking things to "latest" reduces reproducibility as that information may be hard to recover after the fact. For the use case at hand, that may not be relevant.

**Comment by matentzn** [comment]
You are 100% right; its just that ODK is re-released every few days at the moment, and it would be quite a feat to keep a set of jenkins job manually updated.. Reproducibility is less of a concern here imho.. :)

**Comment by kltm** [comment]
fixed in 49b4b52ce9090c39b9035bd18bd3331081beaf2d
