### ISSUE TITLE
Need instructions: Deploy location, how can we download generated release files?

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/pipeline-mp#3]
Is this pipeline actually running successfully? The original jenkis [job](https://build.obolibrary.io/job/obofoundry/job/pipeline-mp) seems to be broken currently;

Few questions:
1) Does the job run whenever mp is changed? If not, how can we configure it to do that?
2) How can we download the release artefacts generated by docker make prepare_release?

**Comment by kltm** [comment]
1) Things like branches and polling frequencies can be defined, but I do not know enough of the workflow to do these myself.
2) This is still TBD depending on the data flow pattern that is desired. For example, these could be pushed to S3, an FTP site, Zenodo, or somewhere else entirely. The only thing that I would suggest positively is that it is to some type of for-purpose file distribution location.

**Comment by matentzn** [comment]
Thanks for the clarification. Just to double check: There is no way in the meantime to serve the generated files on the jenkins server itself in the same way as the BBOB server did? I am worried that if I wait until some enthusiastic soul decided to implement a generic file server solution with Zenodo (since neither you or me will be able to), it could take a bit too long.. Thanks!

**Comment by kltm** [comment]
It can of course be done, but I would consider it on the list of things that are a Bad Idea--given the ephemeral nature of the server, the fact that it behaves poorly as a file server, and how products are created and clobbered, it would be much better to just export files to something like S3, at least until a more robust solution could be found.

**Comment by kltm** [comment]
Now, naturally, that requires the use of an AWS account of some kind. I am not privy to how these things get funded.

**Comment by matentzn** [comment]
@cmungall Can you make a call on this issue? I would really like to move forward on this asap..

**Comment by cmungall** [comment]
If we are going to hook it to S3, we may as well just use travis?

Here is how I envisioned the OBO-Jenkins working

 - Groups can add a Jenkinsfile to their top level (e.g. obophenotype/mammalian-phenotype) [not under OBOFoundry]
 - For groups we trust, we register that file with obo-Jenkins
 - Each group has a workspace. Not sure if we can allocate this on a per group basis or trust people not to flood it.
 - MGI/MP has a weird workflow involving manually copying from a workspace to their FTP. Not ideal but it's what they do
 - a special group is the OBO Services team who may run higher powered integration tests

I had also envisioned this being minimal admin investment on the OBO side; no more than what we have for build.berkeleybop.org (which has a fair amount of initial outlay, but individual jobs such as the old MP incurred virtually no overhead beyond the initial setup).

**Comment by kltm** [comment]
I think that I'd disagree that there is little overhead beyond setup. Due to the way these machines operate, there ends up being a small (but non-trivial) amount of work towards maintenance, sanitation, uptime, etc. By offloading file storage and delivery to an external entity, you actually can take out a lot of the headaches.
All that said, if the expectations for this machine and the users of this machine are appropriately managed, a lot of the same patterns that appear in our "older" Jenkins could be fine here as well.

**Comment by matentzn** [comment]
Thanks, both, for the input!

I can't offer an opinion on the **Jenkins server= File server or not** discussion, because I don't know. I find it a bit excessive to use Zenodo or Github to create releases whenever the Jenkins job is run, which could be multiple times a day. I think on average, the user community wants to retain control on when an ontology should be published, and they don't mind to do that manually (albeit tool support is of course welcome). 

If we want to host these kinds of jobs for the users we need to be able to do three things:
- Manually trigger a release whenever we want (easily)
- Enable the setting: Create a release whenever Master branch X is changed
- Obtain a *configurable set of files* built by the process (make prepare_release creates a vast amount of irrelevant files we definitely do NOT want to share)

At this point, I really dont care how we obtain the files; I just need them soon. Options:
* Gzipped and offered with a link that expires within a few hours; 
* Offered in the usual jenkins style way, 
* Pushed to some file dedicated server
  * OBO hosted (is there such a server we can use)
  * Configurable, hosted by the user (files are pushed using rsync or similar)
  * I think we can agree that OBO foundry will not pay for cloud storage, so let's just ditch that option.
* In the worst case, send as an email :P 

But from the back and forth of this discussion, I assume that we wont solve the problem soon, right? Initially, I thought it was a matter of hours to get this up and running, but seems that we need more discussions.. If that is so: @cmungall can I just use a Monarch Jenkins server to run the MP build in the meantime? Or will this have the exact same problems?

**Comment by kltm** [comment]
@matentzn Sorry to cause confusion here. The current Jenkinsfile, as it stands, can be used in the same way as the current installations that you're used to. If you need to move forward on something, I can help you craft the pipeline-mp Jenkinsfile to support your usecase and start moving forward with *something* now.

I do have discomfort with using Jenkins as a file server and permanent upstream home that screws up other people's pipelines if it goes wrong, but that doesn't mean we can't move forward with development now as we work out details.

**Comment by matentzn** [comment]
Ah great! That is amazing.

So as a minimum spec I need to be able to do this:
1) Checkout MP master branch
2) run the `sh run.sh make prepare_release` in the way you do
3) Download the resulting release artefacts (mp.owl, mp-base.owl, mp.obo, etc) through some form of public page (something like [this](http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/))

I think you already do 1+2, so I only need to know how to do 3 and we are done. I am interested to continue to work on improving things, and I agree with you that both Jenkins and Github have been abused too much as fileservers.

**Comment by kltm** [comment]
@matentzn Okay, I talked to @cmungall a little bit and feel that I have fully had my Festivus-style airing of grievances about being a file provider--I think we're all on the same page for concerns and understanding what we might be signing up for.
I'll try and have a better template for you within the next day.

**Comment by matentzn** [comment]
:) Thanks for all..

**Comment by kltm** [comment]
There are some loose ends, but I believe that this is now a minimally usable base:
https://build.obolibrary.io/job/obofoundry/job/pipeline-mp/
https://build.obolibrary.io/job/obofoundry/job/pipeline-mp/job/master/lastSuccessfulBuild/artifact/
Problems, etc., should probably be new issues from here.
