### ISSUE TITLE
Long standing "Waiting for next available executor"

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/pipeline-mp#6]
In the build records of the job on the jenkins server, that have been running for quite a while. I can see this message:

```
08:01:30  Still waiting to schedule task
08:01:30  Waiting for next available executor
```

Is this a resource limitation problem?

**Comment by kltm** [comment]
Odd as there are two executors and nothing actually running.

**Comment by kltm** [comment]
Okay, I think this is cleared.

I am, however, unclear at why the artifacts do not seem to be changing run to run. This may be a product of something I do not understand in the odk however.
I might suggest a uuid in ontology files as the date may not have the granularity to detect  run changes.
