### ISSUE TITLE
Increase memory for job

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/pipeline-mp#7]
How can I change the main memory limit for the Jenkins job? It is currently not able to perform everything; I think 8GB would suffice! :) thx

**Comment by matentzn** [comment]
The memory increase would have to be both for the job and for docker, now that I thought of it again. :P Thaaaanks!

**Comment by kltm** [comment]
I do not believe there is any job outside the docker image, correct? I believe that the setting would need to be adjusted within the image.

**Comment by matentzn** [comment]
There is one setting: Docker memory; by default it is 2GB. You can set it in the preferences of docker! For OBO foundry work, it should be at least 10, but ideally 16 GB. There is no job outside the docker image, but the docker image is limited by the docker config..

**Comment by kltm** [comment]
@matentzn Hm. I don't believe that to be true. The default setting that we use have jobs that work into the hundreds of GBs. Could you point me to where that is in the in Linux Docker documentation?
My guess is that there is something in how Java is being invoked withing the container.

**Comment by matentzn** [comment]
Ah, I can see probably where my confusion stems from.

In the jenkins file we are running [make all](https://github.com/OBOFoundry/pipeline-mp/blob/c2bbf30a4bb7d6639b2b8634675028f8c65e1d65/Jenkinsfile#L97) from within the container; on travis we run sh run.sh make all from outside the container. This script passes in an environment variable into this run. So I revise the question to: How can I set environment variables before running the script? The corresponding run.sh parameter can be seen [here](https://github.com/obophenotype/mammalian-phenotype-ontology/blob/4092c1d966f910ad18d0f388237792d70358e1d5/src/ontology/run.sh#L12) (ROBOT_JAVA_ARGS).

**Comment by matentzn** [comment]
( You can also set this globally to 16 GB if you prefer)

**Comment by kltm** [comment]
The machine has a hard 16GB limit. Either way, it must be specified in the docker image itself.

**Comment by kltm** [comment]
I'll have a PR in a few minutes.

**Comment by kltm** [comment]
Now 12GB. The job now seems to be failing on its own merit.

**Comment by matentzn** [comment]
Yes!!! This is awesome thanks a lot!
